language: minimal

services:
  - docker

env:
  - OS=ros:melodic-ros-base-bionic
  
before_install:
  - docker pull $OS

script:
  - docker run
      --volume $PWD:/host
      --workdir /host/continuous-integration
      $OS
      bash -c "./setup.sh &&
               ./test.sh"

